export const productData = [
  { title: "nike", price: "2099", id: 1, quantity: 1,size:["L"] },
  { title: "adidas", price: "2399", id: 2, quantity: 2,size:["L"]  },
  { title: "puma", price: "2299", id: 3, quantity: 3 ,size:["L"] },
  { title: "vans", price: "2199", id: 4, quantity: 4,size:["L"]  },
  { title: "nike", price: "2099", id: 11, quantity: 1,size:["L"] },
  { title: "adidas", price: "2399", id: 21, quantity: 2,size:["L"]  },
  { title: "puma", price: "2299", id: 31, quantity: 3 ,size:["X"] },
  { title: "vans", price: "2199", id: 41, quantity: 4,size:["X"]  },
  { title: "nike", price: "2099", id: 12, quantity: 1,size:["X"] },
  { title: "adidas", price: "2399", id: 22, quantity: 2,size:["X","L"]  },
  { title: "puma", price: "2299", id: 32, quantity: 3 ,size:["X"] },
  { title: "vans", price: "2199", id: 42, quantity: 4,size:["X"]  },
  { title: "adidas", price: "2399", id: 23, quantity: 2,size:["XL"]  },
  { title: "puma", price: "2299", id: 33, quantity: 3 ,size:["XL","X"] },
  { title: "vans", price: "2199", id: 43, quantity: 4,size:["XL"]  },
  { title: "nike", price: "2099", id: 14, quantity: 1,size:["XL"] },
  { title: "adidas", price: "2399", id: 24, quantity: 2,size:["XL"]  },
  { title: "puma", price: "2299", id: 34, quantity: 3 ,size:["XL"] },
  { title: "vans", price: "2199", id: 44, quantity: 4,size:["XL"]  },
];
